apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-db-pvc
  namespace: default
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem