apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-app-jira-software
  namespace: default
  resourceVersion: "8860"
  uid: 9129c30e-44f6-4985-a631-aa16b52b33ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: jira-app
      app.kubernetes.io/name: jira-software
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jira-app
        app.kubernetes.io/name: jira-software
    spec:
      containers:
      - env:
        - name: ATL_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ATL_JDBC_PASSWORD
              name: jira-app-jira-software
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
        envFrom:
        - configMapRef:
            name: jira-app-jira-software-cm
        image: atlassian/jira-software:8.21.1
        imagePullPolicy: IfNotPresent
        name: jira-software
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-app-jira-software-home
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until pg_isready -h jira-software-db -p 5432 ; do echo waiting for jira-software-db;
          sleep 5; done;
        image: postgres:9.6.11-alpine
        imagePullPolicy: IfNotPresent
        name: init-postgres
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jira-app-jira-software-home
        persistentVolumeClaim:
          claimName: jira-software-pvc
