apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv
spec:
  capacity:
    storage: 22Gi
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/Code/Kubernetes/Deployments/Storage
